language: node_js
node_js:
  - "node"
addons:
  postgresql: "9.6"
before_install:
  - psql -c 'create database sequelize;' -U postgres
  - npm install -g npm@5.3
script:
  - 'npm test'
after_script: "./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha --report lcovonly test/overall.test.js && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
notifications:
  email:
    recipients:
      - KSDaemon@ya.ru
    on_success: change
    on_failure: always



